services:
  frontend:
    build:
      context: C:/booknest-frontend  #フロントエンドプロジェクトのディレクトリを相対パスまたは、絶対パスにて記載
    container_name: booknest-frontend
    ports:
      - "3000:3000"
    volumes:
      - C:/booknest-frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true

  backend:
    build: C:/pleiades/2024-12/workspace/booknest-backend  # バックエンドプロジェクトのディレクトリを相対パスまたは、絶対パスにて記載
    container_name: booknest-backend
    ports:
      - "8080:8080"
    volumes:
      - C:/pleiades/2024-12/workspace/booknest-backend:/app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/booknest
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: booknest-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: booknest
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  postgres-data:
