import Head from "next/head";
import { Button, TextField, Typography } from "@mui/material";
import { styled } from '@mui/system';
import { FormControl } from '@mui/material';
import { InputLabel, Input, FormHelperText } from '@mui/material';

export default function Home() {
  return (
    <>
      <Head>
        <title>BookNest</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <FormControl>
          <InputLabel htmlFor="my-input">Email address</InputLabel>
          <Input id="my-input" aria-describedby="my-helper-text" />
          <FormHelperText id="my-helper-text">We'll never share your email.</FormHelperText>
          <Button variant="contained">Hello World</Button>
        </FormControl>
        <Typography variant="h1" component="h2">
          BookNest
        </Typography>
      </div>
    </>
  );
}
